### ISSUE TITLE
Doesn't fail when there are errors

### ISSUE THREAD

**Issue by dchinmay2** [nebularg/actions-luacheck#2]
https://github.com/p00f/nvim-ts-rainbow/blob/bab16d47c249de3e72bbb4cfcc212baad78b4848/lua/rainbow.lua

Sorry if i misconfigured the action, but it doesn't fail when it isn't valid lua

**Comment by dchinmay2** [comment]
this is my `.github/workflows/luacheck.yml`
```yml
name: luacheck
on:
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: nebularg/actions-luacheck@v1.1.0
        with:
          annotate: 'warning'
```
